export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const REGISTER_SUPPLIER_START = "REGISTER_SUPPLIER_START";
export const REGISTER_SUPPLIER_SUCCESS = "REGISTER_SUPPLIER_SUCCESS";
export const REGISTER_SUPPLIER_ERROR = "REGISTER_SUPPLIER_ERROR";

export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const AUTH_USER_START = "AUTH_USER_START";

export const SET_MESSAGE = "SET_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";

export const LOGOUT = "LOGOUT";
