export const CONVERSATIONS_OF_USER_START = "CONVERSATIONS_OF_USER_START"
export const CONVERSATIONS_OF_USER_SUCCESS = "CONVERSATIONS_OF_USER_SUCCESS"
export const CONVERSATIONS_OF_USER_ERROR = "CONVERSATIONS_OF_USER_ERROR"
