export const CONVERSATIONS_OF_USER_START = "CONVERSATIONS_OF_USER_START"
export const CONVERSATIONS_OF_USER_SUCCESS = "CONVERSATIONS_OF_USER_SUCCESS"
export const CONVERSATIONS_OF_USER_ERROR = "CONVERSATIONS_OF_USER_ERROR"

export const CREATE_CONVERSATION_START = "CREATE_CONVERSATION_START"
export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS"
export const CREATE_CONVERSATION_ERROR = "CREATE_CONVERSATION_ERROR"

export const GET_REPLIES_OF_CONVERSATION_START = "GET_REPLIES_OF_CONVERSATION_START"
export const GET_REPLIES_OF_CONVERSATION_SUCCESS = "GET_REPLIES_OF_CONVERSATION_SUCCESS"
export const GET_REPLIES_OF_CONVERSATION_ERROR = "GET_REPLIES_OF_CONVERSATION_ERROR"

export const ADD_MSG_IN_REPLIES = "ADD_MSG_IN_REPLIES"
