export const CREATE_CUSTOMER_START = "CREATE_CUSTOMER_START"
export const  CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS"
export const  CREATE_CUSTOMER_ERROR = "CREATE_CUSTOMER_ERROR"

export const GET_ALL_CUSTOMERS_START = "GET_ALL_CUSTOMERS_START"
export const  GET_ALL_CUSTOMERS_SUCCESS = "GET_ALL_CUSTOMERS_SUCCESS"
export const  GET_ALL_CUSTOMERS_ERROR = "GET_ALL_CUSTOMERS_ERROR"

export const UPDATE_CUSTOMER_START = "UPDATE_CUSTOMER_START"
export const  UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS"
export const  UPDATE_CUSTOMER_ERROR = "UPDATE_CUSTOMER_ERROR"


export const DELETE_CUSTOMER_START = "DELETE_CUSTOMER_START"
export const  DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS"
export const  DELETE_CUSTOMER_ERROR = "DELETE_CUSTOMER_ERROR"



