export const ADD_INVENTORY_ITEM_START = "ADD_INVENTORY_ITEM_START";
export const ADD_INVENTORY_ITEM_SUCCESS = "ADD_INVENTORY_ITEM_SUCCESS";
export const ADD_INVENTORY_ITEM_ERROR = "ADD_INVENTORY_ITEM_ERROR";

export const GET_ALL_INVENTORY_ITEMS_START = "GET_ALL_INVENTORY_ITEMS_START";
export const GET_ALL_INVENTORY_ITEMS_SUCCESS =
  "GET_ALL_INVENTORY_ITEMS_SUCCESS";
export const GET_ALL_INVENTORY_ITEMS_ERROR = "GET_ALL_INVENTORY_ITEMS_ERROR";

export const UPDATE_INVENTORY_ITEM_START = "UPDATE_INVENTORY_ITEM_START";
export const UPDATE_INVENTORY_ITEM_SUCCESS = "UPDATE_INVENTORY_ITEM_SUCCESS";
export const UPDATE_INVENTORY_ITEM_ERROR = "UPDATE_INVENTORY_ITEM_ERROR";

export const DELETE_INVENTORY_ITEM_START = "DELETE_INVENTORY_ITEM_START";
export const DELETE_INVENTORY_ITEM_SUCCESS = "DELETE_INVENTORY_ITEM_SUCCESS";
export const DELETE_INVENTORY_ITEM_ERROR = "DELETE_INVENTORY_ITEM_ERROR";
