export const GET_ALL_SUPPLIER_SALES_START = "GET_ALL_SUPPLIER_SALES_START";
export const GET_ALL_SUPPLIER_SALES_SUCCESS = "GET_ALL_SUPPLIER_SALES_SUCCESS";
export const GET_ALL_SUPPLIER_SALES_ERROR = "GET_ALL_SUPPLIER_SALES_ERROR";
