export const CREATE_SUPPLIER_START = "CREATE_SUPPLIER_START";
export const CREATE_SUPPLIER_SUCCESS = "CREATE_SUPPLIER_SUCCESS";
export const CREATE_SUPPLIER_ERROR = "CREATE_SUPPLIER_ERROR";

export const GET_ALL_SUPPLIERS_START = "GET_ALL_SUPPLIERS_START";
export const GET_ALL_SUPPLIERS_SUCCESS = "GET_ALL_SUPPLIERS_SUCCESS";
export const GET_ALL_SUPPLIERS_ERROR = "GET_ALL_SUPPLIERS_ERROR";

export const GET_ALL_NEARBY_SUPPLIERS_START = "GET_ALL_NEARBY_SUPPLIERS_START";
export const GET_ALL_NEARBY_SUPPLIERS_SUCCESS =
  "GET_ALL_NEARBY_SUPPLIERS_SUCCESS";
export const GET_ALL_NEARBY_SUPPLIERS_ERROR = "GET_ALL_NEARBY_SUPPLIERS_ERROR";

export const GET_SUPPLIER_INVENTORY_ITEMS_START =
  "GET_SUPPLIER_INVENTORY_ITEMS_START";
export const GET_SUPPLIER_INVENTORY_ITEMS_SUCCESS =
  "GET_SUPPLIER_INVENTORY_ITEMS_SUCCESS";
export const GET_SUPPLIER_INVENTORY_ITEMS_ERROR =
  "GET_SUPPLIER_INVENTORY_ITEMS_ERROR";

export const UPDATE_SUPPLIER_START = "UPDATE_SUPPLIER_START";
export const UPDATE_SUPPLIER_SUCCESS = "UPDATE_SUPPLIER_SUCCESS";
export const UPDATE_SUPPLIER_ERROR = "UPDATE_SUPPLIER_ERROR";

export const DELETE_SUPPLIER_START = "DELETE_SUPPLIER_START";
export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";
export const DELETE_SUPPLIER_ERROR = "DELETE_SUPPLIER_ERROR";
