export const USERS_FOR_CONVERSATIONS_START = "USERS_FOR_CONVERSATIONS_START"
export const  USERS_FOR_CONVERSATIONS_SUCCESS = "USERS_FOR_CONVERSATIONS_SUCCESS"
export const  USERS_FOR_CONVERSATIONS_ERROR = "USERS_FOR_CONVERSATIONS_ERROR"

